language: go

go:
    - "1.14.x"
    - "1.13.x"
    - "1.12.x"
    - "1.11.x"

before_install:
    - mkdir -p /home/travis/gopath-tmp
    - export GOPATH="/home/travis/gopath-tmp"

script:
    - make all coveralls
